---
title: "Lab 3"
date: last-modified
format: 
  html:
    code-overflow: wrap
---

# General Instructions

- Submit your work via [Canvas](https://canvas.case.edu/). 
- The deadline for this Lab is specified on the [Course Calendar](calendar.qmd).
  - We charge a 5 point penalty for a lab that is 1-48 hours late.
  - We do not grade work that is more than 48 hours late.
- Your response should include a Quarto file (.qmd) and an HTML document that is the result of applying your Quarto file to the data we've provided.

:::{.callout-important}

You can skip exactly one of Labs 1-5 without penalty, but all students must complete both Lab 6 and Lab 7. If you decide to skip a lab, please submit a note to Canvas by the deadline saying that you are skipping the lab.

:::

## Template

There is a [Lab 3 Quarto template](https://raw.githubusercontent.com/THOMASELOVE/432-data/refs/heads/master/data/432_lab3_template.qmd) available on [our 432-data page](https://github.com/THOMASELOVE/432-data). Please use the template to prepare your response to Lab 3, as it will make things easier for you and for the people grading your work.

- In the Lab 3 template, we use the `united` theme. If you'd like to use a different theme, [the available list is here](https://quarto.org/docs/output-formats/html-themes.html).

## Our Best Advice

Review your HTML output file carefully before submission for copy-editing issues (spelling, grammar and syntax.) Even with spell-check in RStudio (just hit F7), it's hard to find errors with these issues in your Quarto file so long as it is running. You really need to look closely at the resulting HTML output.

## The Data

- The `nh_1500` R data set is available for download on the [432 data page](https://github.com/THOMASELOVE/432-data).
- A detailed description of each variable in the `nh_1500` (and also the `nh_3143`) data is [available here](nhanes_codebook.qmd).

# Question 1 (25 points)

In question 1, you will evaluate a linear regression fit in the `nh_1500` data to predict a subject's red blood cell count (please use `rbc`, untransformed, as the outcome for all of Question 1) using these five predictors:

- the subject's sex,
- the subject's race/ethnicity,
- the subject's waist circumference,
- the subject's pulse rate, and
- whether or not the subject has smoked 100 cigarettes in their life

Note that the main effects model using all five of these predictors will use 7 degrees of freedom, since there are four race/ethnicity categories, and the other four variables are all either binary or quantitative.

a. {9 points} Use a Spearman $\rho^2$ plot to identify a single non-linear term which could be added to the model. Your selected non-linear term may add at most 3 degrees of freedom to the main effects model. Specify the added term clearly, and then fit both the main effects model (call it `m1_main`) and the model with your non-linear term (call it `m1_add`) using both `ols()` and `lm()`.

b. {8} Which of the two models you fit in part a. appears to do a better job, when evaluated using bootstrap validation in the development sample? Why? An appropriate response will compare the models in terms of validated R-square and MSE values using 40 bootstrap replications. Set your seed to be `set.seed(20251)` for your main effects model, and `set.seed(20252)` for your model adding a non-linear term.

c. {8} Using a 90% confidence level, plot the effect summary (using `plot(summary(modelname, conf.int = 0.90))` after an `ols()` fit) for the model you preferred in part b, and then show the corresponding tabular summary of effect size estimates. State and fully explain the meaning of the `pulse` effect shown in your output in a complete English sentence or two.

# Question 2 (25 points)

Again using the `nh_1500` data, we will now build a set of logistic regression models to predict whether a subject is limited in the kind or amount of work they can do by a physical, mental or emotional problem. 

a. {10} Build a model to predict `limited` on the basis of self-reported overall health. Call this `model2a`. Then add the main effects of white blood cell count, waist circumference and age to the model and call this new model `model2b`.

b. {10} Interpret the odds ratio associated with self-reported overall health being Excellent as compared to being Good in *each* of your two models, and provide a 90% confidence interval for each such estimate.

c. {5} As measured by a validated C statistic using a seed of `4321` for `model2a` and `4322` for `model2b` and 40 bootstrap replications in each case, which model performs better, `model2a` or `model2b`, and why? Be sure to specify your validated C statistics for each model. 

# Use of AI

If you decide to use some sort of AI to help you with this Lab, we ask that you place a note to that effect, describing what you used and how you used it, as a separate section called "Use of AI", after your answers to our questions, and just *before* your presentation of the Session Information. Thank you.

## Be sure to include Session Information

Please display your session information at the end of your submission, as shown below.

```{r}
xfun::session_info()
```

## After the Lab

- We will post an answer sketch to our Shared Google Drive 48 hours after the Lab is due.
- We will post grades to our Grading Roster on our Shared Google Drive one week after the Lab is due.
- See the Lab Appeal Policy in our Syllabus if you are interested in having your Lab grade reviewed, and use the Lab Regrade Request form specified there to complete the task. Thank you.