---
title: "Lab 4"
date: last-modified
format: 
  html:
    code-overflow: wrap
---

# General Instructions

- Submit your work via [Canvas](https://canvas.case.edu/). 
- The deadline for this Lab is specified on the [Course Calendar](calendar.qmd).
  - We charge a 5 point penalty for a lab that is 1-48 hours late.
  - We do not grade work that is more than 48 hours late.
- Your response should include a Quarto file (.qmd) and an HTML document that is the result of applying your Quarto file to the data we've provided.

:::{.callout-important}

You can skip exactly one of Labs 1-5 without penalty, but all students must complete both Lab 6 and Lab 7. If you decide to skip a lab, please submit a note to Canvas by the deadline saying that you are skipping the lab.

:::

## Template

You should be able to modify any of the first three Lab templates available on [our 432-data page](https://github.com/THOMASELOVE/432-data) to help you do this Lab. Feel encouraged to try a [different HTML theme](https://quarto.org/docs/output-formats/html-themes.html) if you like, maybe [yeti](https://bootswatch.com/yeti/) or [spacelab](https://bootswatch.com/spacelab/) or [materia](https://bootswatch.com/materia/). 

## Our Best Advice

Review your HTML output file carefully before submission for copy-editing issues (spelling, grammar and syntax.) Even with spell-check in RStudio (just hit F7), it's hard to find errors with these issues in your Quarto file so long as it is running. You really need to look closely at the resulting HTML output.

## The Data

- The `hbp_3024.xlsx` Excel file (first introduced in [Lab 2](lab2.qmd)) is available for download on the [432 data page](https://github.com/THOMASELOVE/432-data). Be sure that you see 8 variables with missing values when you impute the data.
- A detailed description of each variable in the `hbp_3024` data is [available here](hbp_codebook.qmd).

# Question 1 (5 points)

Begin with the `hbp_3024` data, but include only the 1,296 subjects with who were seen by either the Center, Elm, or Walnut practices. Next, develop a single imputation strategy using the `mice` package and a seed of `2025` to account for missing values. Call the resulting imputed data set `hbp_lab4`. Show your R code, and demonstrate that the following three things are true...

- your `hbp_1` data has no missing values, 
- within `hbp_1`, the practices have 88, 121 and 156 subjects with a depression diagnosis, respectively, and
- both the mean and standard deviation of `income` is lower in the subjects with a depression diagnosis than in the subjects without.

:::{.callout-note}
You'll use the `hbp_1` data in Questions 1 and 2 of this Lab.
:::

# Question 2 (20 points)

Using the `hbp_1` data, build a logistic regression model, called `fit1`, to predict whether a subject has a depression diagnosis based on the main effects of four variables:

- which of the four practices they receive care from, along with
- the subject’s age,
- the subject’s tobacco use status, and
- the estimated percentage of adults living in the subject’s home neighborhood who have graduated from high school (the `hsgrad` variable)

a. {5} What is the area under the ROC curve for `fit1`? Interpret the meaning of that C statistic in a complete English sentence.

b. {5} Specify the best one choice of non-linear term to add to the `fit1` model, according to a Spearman $\rho^2$ plot. Specify and justify your choice of non-linear term, and specify how many degrees of freedom your term add to `fit1`?

c. {5} Fit the model including the term you added in part b, and call that model `fit2`. What do the AIC and BIC statistics for `fit2` suggest to you as compared to those values in `fit1`?

d. {5} For the model which looks better to you according to part c, use a decision rule that you will predict a depression diagnosis if the predicted probability of such a diagnosis according to your model exceeds 0.4. Now, across the `hbp_1` sample, specify the sensitivity, specificity and accuracy of this prediction rule.

# Question 3 (25 points)

Starting again from the `hbp_3024` data, partition the data into:

- a training sample, which I would call `hbp_train`, including the subjects seen in the Highland, King, Plympton or Sycamore practices, and 
- a test sample, which I would call `hbp_test`, consisting of the remaining three practices (Center, Elm, or Walnut practices.)

You will build two models to predict diastolic blood pressure (potentially using an outcome transformation) on the basis of:

- in model `fit3`: the subject's age, LDL cholesterol level, tobacco status, insurance status, and whether or not they had a beta-blocker prescription. 
- in model `fit4`: the subject's age and LDL cholesterol level alone.

a. {5} Use an appropriate tool to make a decision about a transformation of your outcome and describe your conclusions from that tool.

b. {5} Using the transformed outcome you identified in part a., fit models `fit3` and `fit4` in your training sample, and compare the two models in terms of AIC, BIC, adjusted $R^2$ and sigma. Use these four summaries to help you decide which of the two models (`fit3` or `fit4`) shows better training sample performance.

c. {5} Compare the performance of your two models (`fit3` and `fit4`) in the test sample, using the following four summaries of prediction error: MAPE, Maximum absolute prediction error, RMSPE and validated $R^2$. According to these measures, which model looks better in terms of fit in the test sample?

d. {10} Select a winning model based on your results in parts b and c, and refit that model now using the whole sample from `hbp_3024` and 20 multiple imputations developed using the `mice` package, with the seed `202543204`. Specify the point estimate of the `LDL` effect, as well as its 90% confidence interval, after this imputation process, and interpret the meaning of the point estimate in a complete sentence or two.

# Use of AI

If you decide to use some sort of AI to help you with this Lab, we ask that you place a note to that effect, describing what you used and how you used it, as a separate section called "Use of AI", after your answers to our questions, and just *before* your presentation of the Session Information. Thank you.

## Be sure to include Session Information

Please display your session information at the end of your submission, as shown below.

```{r}
xfun::session_info()
```

## After the Lab

- We will post an answer sketch to our Shared Google Drive 48 hours after the Lab is due.
- We will post grades to our Grading Roster on our Shared Google Drive one week after the Lab is due.
- See the Lab Appeal Policy in our Syllabus if you are interested in having your Lab grade reviewed, and use the Lab Regrade Request form specified there to complete the task. Thank you.