---
title: "Quiz 1"
---

## Points of Clarification after the Quiz went out

:::{.callout-note}

Things that appear here will also be emailed to all students. Emails will be sent at most daily, while this location will be updated more frequently, as needed.

:::

1. A main effects model contains only main effects. **Question 4** is asking you to fit a specific model with four specified main effects included, not to look around for other potential models, or consider things other than main effects. There are numerous places, including (but not limited to) the model called `fit13a` in **Question 14**, and the model in **Question 20**, where my instructions tell you precisely which model to fit. - *posted 2025-02-28*

2. When partitioning with a requirement for a certain distribution of a variable, the split the computer creates may one or two numbers away from the goal in terms of the sizes of your training and testing samples, in order to maintain the closeness of the variable distributions. That's OK. Being within one or two people of 175 in the training group and within one or two people of 50 in the testing group in **Question 11** is fine. - *posted 2025-02-28*

3. Power is virtually always expressed as a percentage, between 0 and 100. In question 17, you should express it in that fashion, with zero decimal places. So, for example, if the calculated power was 0.53, your answer would be 53. - *posted 2025-02-28*

4. The original version of the Google Form Answer Sheet had no place to respond to Question 7b, and forced a single choice instead of allowing multiple choices for Question 16. This is now fixed. - *posted 2025-02-28*

## Instructions

Quiz 1 covers materials from Classes 1-14 of the course, as well as Jeff Leek's [How to be a modern scientist](https://leanpub.com/modernscientist), and other sources assigned during classes 1-14.

All Quiz 1 elements are now available.

1. The main document (pdf) for Quiz 1, which includes both instructions and all of the questionsm, is in our Shared Drive in a folder called **432 Quiz 1 Materials (due 2025-03-05 at noon)**. Look for the file named `432-quiz1-2025.pdf`.
2. The Google Form Answer Sheet for Quiz 1 is at <https://bit.ly/432-2025-quiz1-answer-sheet>, and this is where you will submit your responses.
3. The three Data Sets for Quiz 1 are in our Shared Drive. Look in the folder called **432 Quiz 1 Materials (due 2025-03-05 at noon)** for a **data** sub-folder, where you should find data sets named `dat_A.csv`, `dat_B.xlsx` and `dat_C.Rds`.

Quiz 1 is due on Wednesday 2025-03-05 at Noon.

## How do I get help?

This is an open book, open notes quiz. You are welcome to consult the materials provided on the course website and that we've been reading in the class, but you are not allowed to discuss the questions on this quiz with anyone other than Professor Love and the teaching assistants. You will complete a short affirmation that you have obeyed these rules as part of submitting the Quiz.

If you need clarification on a Quiz question, you have exactly two ways of getting help:

- You can ask your question via email to **Thomas dot Love at case dot edu**, or
- You can ask your question of Dr. Love directly in class 15 on 2025-03-04.

During the Quiz period (2024-02-27 through 2024-03-05) we will not answer questions about Quiz 1 except through the email and class session above. 

- Please check your email **and** the [Quiz 1 links page](https://thomaselove.github.io/432-2025/quiz1.html) *before* submitting the final version of your Quiz, to see if Dr. Love has posted any changes there. 
- Dr. Love promises to respond to all questions received before 9 AM on 2024-03-05 (three hours before the Quiz is due) in a timely fashion.
