---
title: "Quiz 2"
---

## Corrections and Other Edits after initial posting of Quiz 2 

will be listed here as they occur. Dr. Love will email all students if a substantial change is required.

- The original version of the main document PDF was typeset `2025-04-18 at 02:55 PM`.

**Most Recent Update to PDF**: typeset Monday `2025-04-21 at 1:49 PM`

### Question 1 (last change Sunday 2025-04-20)

- Option `a` in **Question 1** is now corrected in the PDF and the Answer Form to read: a. The lowest numbered **subject code** for a censored subject in data1 is 6.
    - The original version referred to a non-existent `ptid`.
- Option `f` in Question 1 now is written as: "f. The legends and colors on the risk table in Display 2 **do not** match those shown to describe the main plot in Display 2." to help clarify the issue.

### Question 5 (last change Saturday 2025-04-19)

- I deleted the word **different** in the last part of Question 5 option `b`. It now reads: "How many subjects should be included in your `new5` tibble?"

### Question 9

**Hint**: If one of the indicator variables for a multi-categorical predictor is included in the "best subsets" result for Question 9, include the entire multi-categorical predictor in the model you select.

### Question 10 (last change Sunday 2025-04-20)

I have changed the first paragraph of Question 10 to read:

Using the `data3` tibble, build an appropriate pair of models to predict `ecig_s` for that tibble, one of which assumes proportional odds and one of which does not, using the following five predictors: `age`, `female`, `race_eth`, `educ`, and `asthma`. 

**Hint**: A correct answer to Question 10 includes the data from subject `H012304`, who is in the 172nd row of the `data3` tibble.

### Question 12 (last change Sunday 2025-04-20)

I emphasized that your response should describe, in detail, the meaning of both the point estimate **and** the 99% confidence interval, in parts a and b of Question 12, which now read:

a. Write a complete sentence or two to describe the meaning of both the point estimate **and** the 99% confidence interval for the `mode` effect in model `m12`.

b. Write a complete sentence or two to describe the meaning of both the point estimate **and** the 99% confidence interval for the danceability (`dance`) effect in model `m12`.

I will be looking to see that you accurately describe the meaning of both the point estimate and the 99% confidence interval.

Note that an excellent answer to Question 12 will show that you've reviewed the description of the variables contained in `data4`.

### Question 20 (last change Monday 2025-04-21)

In the initial version, there was a reference to happiness, which is not part of the question. The new final sentence in the first paragraph is now:

Use `m20` to predict the levels of financial satisfaction (`satfin`) for the `data6` tibble's subjects.

## Material needed to complete Quiz 2

1. The main document (pdf) for Quiz 2, which includes instructions, descriptions of the data sets, and all 25 questions is now available in the **432 Quiz 2 Materials (due 2025-04-28 at 9 AM)** folder on our Shared Drive. The PDF file for this main document is called **432-quiz2-2025.pdf** and is **52** pages long.

2. The link to the Google Form Answer Sheet for Quiz 2 is <https://bit.ly/432-2025-quiz2-form> and this is where you will submit your responses. Quiz 2 is due at **9 AM on Monday 2025-04-28**. The [Google Form](https://bit.ly/432-2025-quiz2-form) will close at 9:30 AM that day, and will not re-open.

3. We have provided six data sets for Quiz 2. Descriptions of the data sets are available in the main document. To download the data, visit the **432 Quiz 2 Materials (due 2025-04-28 at 9 AM)** folder on our Shared Drive. In the **data** subfolder, you will find:
    - `data1.Rds`, which should include 146 observations on 11 variables.
    - `data2.csv`, which should include 2265 observations on 15 variables.
    - `data3.xlsx`, which should include 902 observations on 9 variables.
    - `data4.dta`, which should include 2482 observations on 9 variables.
    - `data5.sav`, which should include 2787 observations on 9 variables.
    - `data6.csv`, which should include 1362 observations on 7 variables.

4. To save you some typing, we have also provided Quarto and HTML versions of a document called **starting_quiz_2**. To download the files, visit the **432 Quiz 2 Materials (due 2025-04-28 at 9 AM)** folder on our Shared Drive. This document provides the following code elements (also provided in the main document PDF):
    - the complete setup (R packages, etc.) used by Professor Love to build the quiz and its answer sketch,
    - all code necessary to download the six data sets to create the tibbles used in the quiz, and
    - some of the code necessary to complete Question 9

We suggest you use the **starting_quiz_2** Quarto file to get started developing answers for the Quiz questions. The HTML version is provided so that you can see what the results of using the Quarto file should look like before you answer any of the questions.

## Other Details on Quiz 2

Quiz 2 covers materials from Classes 1-23 of the course, as well as Jeff Leek's [How to be a modern scientist](https://leanpub.com/modernscientist), and other sources assigned during classes 1-23.

Again, Quiz 2 is due at 9 AM on Monday 2025-04-28. The [Google Form](https://bit.ly/432-2025-quiz2-form) will close at 9:30 AM that day, and will not re-open, so you have 30 minutes leeway.

If you have a question about Quiz 2, send it by email to Dr. Love at `thomas dot love at case dot edu`.

Good luck!
